DEFAULT:
  model: "resnet"
  resnet_depth: 50
  lr: 0.0002
  batch_size: 1
  epochs: 70
  data_path: "../Dataset/ninacustom_20m_v0_SR/"
  note: "400x400 ninacustom 10m only grid search!"
  num_inputs: 4
