DEFAULT:
  model: "resnet"
  lr: 0.0001
  batch_size: 1
  epochs: 500
  data_path: "../Dataset/Formatted/"
  note: "Re-doing training on formatted images with no shuffling of channels and with better normalisation"
  num_inputs: 12