DEFAULT:
  model: "ninab1"
  scale: 2.0
  lr: 0.00001
  batch_size: 1
  epochs: 50
  sample_size: 10
  channel_subset: False
  channel_select: [4, 5, 6, 7, 8, 9]
  loss_fn: "psnr"
  note: "nina2b on 20m res images"