DEFAULT:
  model: "nina2b"
  scale: 2.0
  lr: 0.00001
  batch_size: 1
  epochs: 50
  sample_size: 500
  channel_subset: True
  channel_select: [10, 11]
  loss_fn: "psnr"
  note: "nina2b on 60m res images"