DEFAULT:
  model: "ninab2"
  scale: 2.0
  lr: 0.00001
  batch_size: 1
  epochs: 5000
  sample_size: 50
  one_channel: False
  channel_select: 3
  loss_fn: "psnr"
  note: "Layers are frozen again for testing"