DEFAULT:
  model: "rcan"
  scale: 2.0
  lr: 0.00001
  batch_size: 1
  epochs: 50
  sample_size: 500
  one_channel: True
  channel_select: 3
  loss_fn: "mse"
  note: "Trying rcan with only channel 3 which is highest resolution"