DEFAULT:
  model: "edsr_20m"
  scale: 2.0
  lr: 0.00005
  batch_size: 1
  epochs: 200
  sample_size: 100
  channel_subset: True
  channel_select: [4, 5, 6, 7, 8, 9]
  loss_fn: "mse"
  note: "edsr ChannelSR"
